name: Compile and Commit PDF

on:
  push:
    branches:
      - main
    paths:
      - '**.tex'
      - '**.yml'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-commit-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Install TeX Live
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tex/resume.tex

      - name: Install Full TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile LaTeX document
        run: |
          mkdir out
          latexmk -pdf -outdir=out -interaction=nonstopmode tex/resume.tex

      - name: Commit PDF to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch
          git checkout main
          git add resume.pdf
          git commit -m "Automatically update PDF"
          git push origin main

          git fetch
          git checkout prod
          git add resume.pdf
          git commit -m "Automatically update PDF"
          git push origin prod


