name: Compile and Commit PDF

on:
  push:
    branches:
      - main
    paths:
      - '**.tex'

jobs:
  build-and-commit-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Install TeX Live
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ../../resume.tex

      - name: Compile LaTeX document
        run: latexmk -pdf ../../resume.tex

      - name: Commit PDF to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add resume.pdf
          git commit -m "Automatically update PDF"
          git push
